# govulncheck ./...
name: govulncheck
on:
  push:
    branches:
      - "dev"
      - "main"

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Scan for Vulnerabilities in Code
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.22.3
          go-package: ./...
