name: CI Main

on:
  push:
    branches: ["main"]

env:
  VERSION: v0.2.4
  REPO: vcr.vngcloud.vn/81-vks-public

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: vngcloud-ingress-controller
          - image: vngcloud-controller-manager
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the vCR
        uses: docker/login-action@v3
        with:
          registry: vcr.vngcloud.vn
          username: ${{ secrets.VCR_USER_PRO }}
          password: ${{ secrets.VCR_PASSWORD_PRO }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/vngcloud/${{ matrix.image }}:${{ github.sha }}
            ${{ env.REPO }}/${{ matrix.image }}:${{ github.sha }}
            ${{ env.REPO }}/${{ matrix.image }}:${{ env.VERSION }}
          target: ${{ matrix.image }}
