name: Release

# git tag v1.0.0
# git push origin v1.0.0

on:
  push:
    tags:
      - "v*" # Triggers on version tags, e.g., v1.0.0
# env:
#   REPO: vcr.vngcloud.vn/81-vks-public

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: vngcloud-ingress-controller
          - image: vngcloud-controller-manager
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Log in to the GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run: echo ${{ github.ref_name }}

      # - name: Fetch All Tags
      #   run: git fetch --tags

      # - name: Get Latest Tag
      #   id: get_latest_tag
      #   run: echo "latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      # - name: Display Latest Tag
      #   run: echo "The latest tag is ${{ env.latest_tag }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          platforms: linux/amd64
          outputs: type=registry
          tags: |
            ghcr.io/${{ github.actor }}/${{ matrix.image }}:${{ github.ref_name }}
          target: ${{ matrix.image }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "${{ github.ref_name }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ github.ref_name }}" \
              --generate-notes

# ${{ env.REPO }}/${{ matrix.image }}:${{ github.sha }}
# ${{ env.REPO }}/${{ matrix.image }}:${{ github.ref_name }}
